name: Fetch Fortnite API

on:
    schedule:
      - cron: '*/10 * * * *'

jobs:
  fetch_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Fortnite API
        run: python fetch_spark_tracks.py

      - name: Archive response content
        uses: actions/upload-artifact@v2
        with:
          name: SparksTracks
          path: transformed_data.json

      - name: Commit and push artifact
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add transformed_data.json timestamp.json
          git commit -m "Update spark tracks"
          git push
